### ISSUE TITLE
[ENHANCEMENT] - NFT card title and description needs to be cut when too long

### ISSUE THREAD

**Issue by xscottxbrownx** [alchemyplatform/cw3d-nft-explorer#3]
<img width="1286" alt="Screenshot 2023-03-02 at 5 57 06 PM" src="https://user-images.githubusercontent.com/71395931/222612590-d3e3767d-0125-4881-9943-e18533d8604c.png">
<img width="1378" alt="Screenshot 2023-03-02 at 5 57 45 PM" src="https://user-images.githubusercontent.com/71395931/222612606-467bc2de-af76-4028-bdf2-81c560b78edd.png">

If the title of the NFT is too long, it just overflows off the card and into next.

If the symbol is too long, it messes with the whole container and everything is misaligned and can go off the card entirely.

**Within the nftGallery > NFT Card component**

**Comment by Eversmile12** [comment]
PR Approved!
