### ISSUE TITLE
[BUG] - Load More button doesn't actually load more, it loads page 2

### ISSUE THREAD

**Issue by xscottxbrownx** [alchemyplatform/cw3d-nft-explorer#7]
When a wallet contains too many NFTs to display on the first page of results in the NFT Gallery, it has a `Load More` button at the bottom of the gallery.  

But when you click this button, it displays the NEXT 100 NFTs, **not** 100 MORE NFTs.

__And there's no way to go back to the first 100.__

So, solution seems to be 2 options:

1) actually load the next 100 NFTS below the first 100 (which Load More seems to mean/denote)
OR
2) load the next 100 NFTS (like it does now) but have pagination - a way to click back to page 1 and on page 1 a way to click to page 2 of these displayed NFTs.

**Comment by Eversmile12** [comment]
On it!

**Comment by Eversmile12** [comment]
Solved here [714ec06ce](https://github.com/alchemyplatform/cw3d-nft-explorer/commit/714ec06ce3916cd194876223d1858c1101b6dbdc) - thanks!
